<a href="https://colab.research.google.com/github/Exion007/Colab/blob/main/pokemon_df_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import os
import time
import pickle
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, log_loss
from sklearn.ensemble import BaggingClassifier, GradientBoostingClassifier, RandomForestClassifier

In [32]:
df = pd.read_csv("pokemon.csv")

df["Type 2"].fillna("None", inplace = True)

df = df.iloc[:,2:23]
df = df.drop(columns=["Abilities", "Mean", "Standard Deviation"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Type 1                   1032 non-null   object
 1   Type 2                   1032 non-null   object
 2   HP                       1032 non-null   int64
 3   Att                      1032 non-null   int64
 4   Def                      1032 non-null   int64
 5   Spa                      1032 non-null   int64
 6   Spd                      1032 non-null   int64
 7   Spe                      1032 non-null   int64
 8   BST                      1032 non-null   int64
 9   Generation               1032 non-null   float64
 10  Experience type          1032 non-null   object
 11  Experience to level 100  1032 non-null   int64
 12  Final Evolution          1032 non-null   float64
 13  Catch Rate               1032 non-null   int64
 14  Legendary                1032 non-null   float64
 15  Mega Evolution           1032 non-null   float64
 16  Alolan Form              1032 non-null   float64
 17  Galarian Form            1032 non-null   float64
dtypes: float64(6), int64(9), object(3)
memory usage: 145.2+ KB

In [33]:
print(df["Type 1"].unique(), "\n")
print(df["Type 2"].unique(), "\n")
print(df["Experience type"].unique(), "\n")
print(np.sort(df["Experience to level 100"].unique()), "\n")
print(np.sort(df["Catch Rate"].unique()), "\n")

['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Dark' 'Poison' 'Electric' 'Ground'
 'Ice' 'Fairy' 'Steel' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Dragon'
 'Flying']

['Poison' 'None' 'Flying' 'Dragon' 'Normal' 'Psychic' 'Steel' 'Ground'
 'Fairy' 'Grass' 'Fighting' 'Electric' 'Ice' 'Dark' 'Ghost' 'Rock' 'Water'
 'Fire' 'Bug']

['Medium Slow' 'Medium Fast' 'Fast' 'Slow' 'Fluctuating' 'Erratic']

[ 600000  800000 1000000 1059860 1250000 1640000]

[  3  10  15  25  30  35  45  50  55  60  65  70  75  80  90 100 120 125
 127 130 140 145 150 155 160 170 180 190 200 205 220 225 235 255]

In [34]:
le = LabelEncoder()
df["Type 1"] = le.fit_transform(df["Type 1"])
df["Type 2"] = le.fit_transform(df["Type 2"])
df["Generation"] = le.fit_transform(df["Generation"]) + 1
df["Final Evolution"] = le.fit_transform(df["Final Evolution"])
df["Experience type"] = le.fit_transform(df["Experience type"])
df['Legendary'] = le.fit_transform(df['Legendary'])
df['Mega Evolution'] = le.fit_transform(df['Mega Evolution'])
df['Alolan Form'] = le.fit_transform(df['Alolan Form'])
df['Galarian Form'] = le.fit_transform(df['Galarian Form'])
df.head(10)

,Type 1,Type 2,HP,Att,Def,Spa,Spd,Spe,BST,Generation,Experience type,Experience to level 100,Final Evolution,Catch Rate,Legendary,Mega Evolution,Alolan Form,Galarian Form
0,9,14,45,49,49,65,65,45,318,1,4,1059860,0,45,0,0,0,0
1,9,14,60,62,63,80,80,60,405,1,4,1059860,0,45,0,0,0,0
2,9,14,80,82,83,100,100,80,525,1,4,1059860,1,45,0,0,0,0
3,9,14,80,100,123,122,120,80,625,6,4,1059860,1,45,0,1,0,0
4,6,12,39,52,43,60,50,65,309,1,4,1059860,0,45,0,0,0,0
5,6,12,58,64,58,80,65,80,405,1,4,1059860,0,45,0,0,0,0
6,6,7,78,84,78,109,85,100,534,1,4,1059860,1,45,0,0,0,0
7,6,7,78,104,78,159,115,100,634,6,4,1059860,1,45,0,1,0,0
8,6,2,78,130,111,130,85,100,634,6,4,1059860,1,45,0,1,0,0
9,17,12,44,48,65,50,64,43,314,1,4,1059860,0,45,0,0,0,0

In [36]:
df.to_csv("pokemon_df.csv", index = False)